---
#
- hosts: all
  become: yes

  vars:
    TAG_ID: 1.30.0
    configure_vaultwarden: true


  vars_files:
    - group_vars/password_vault.yml


  roles:
    - name: ansible-vaultwarden-caddy

#  tasks:
#    - include_role:
#        name: ansible-vaultwarden-caddy
#
